[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/tmdb"
  to = "/.netlify/functions/tmdb"
  status = 200

[[redirects]]
  from = "/api/watchmode"
  to = "/.netlify/functions/watchmode"
  status = 200

[[redirects]]
  from = "/api/youtube"
  to = "/.netlify/functions/youtube"
  status = 200